tutorial/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done,
    password_reset_confirm, password_reset_complete
)

# defining a name for url can avoid hard coding url address by using the reverse function
urlpatterns = [
    url(r'^$',views.home),
    # args: defined url, which view in django to overwirte, html template to use
    url(r'^login/$', login,{'template_name': 'accounts/login.html'}, name = 'login'),
    url(r'^logout/$', logout,{'template_name': 'accounts/logout.html'}, name = 'logout'),
    url(r'^register/$', views.register, name = 'register'),
    # show the user info
    # if user wants to edit his info, may need to write another form.py
    url(r'^profile/$', views.view_profile, name = 'view_profile'),
    # a page that the user can edit his profile info
    url(r'^profile/edit/$', views.edit_profile, name = 'edit_profile'),
    # a page that allows the user change his password
    url(r'^change-password/$', views.change_password, name = 'change_password'),

    # below 4 urls call each other automatically when an action has been made
    url(r'^reset-password/$', password_reset,{'template_name': 
    # need to overwrite the 'post_reset_redirect' in the django built-in template,
    # otherwise the page doesn't work
    'accounts/reset_password.html', 
    'post_reset_redirect':'accounts:password_reset_done',
    'email_template_name':'accounts/reset_password_email.html'} ,name = "reset_password"),
    
    url(r'^reset-password/done/$', password_reset_done, 
    {'template_name': 'accounts/reset_password_done.html'}, name = "password_reset_done"),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 
    password_reset_confirm, {'template_name': 
    'accounts/reset_password_confirm.html', 'post_reset_redirect':
    'accounts:password_reset_complete'}, name = "password_reset_confirm"),

    url(r'^reset-password/complete/$', 
    password_reset_complete, {'template_name': 
    'accounts/reset_password_complete.html'}, name = "password_reset_complete"),
]

tutorial/tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from tutorial import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login_redirect, name = 'login_redirect'),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),  
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tutorial/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length = 100, default = '')
    city = models.CharField(max_length = 100, default = '')
    website = models.URLField(default = '')
    phone = models.IntegerField(default = 0)
    image = models.ImageField(upload_to = 'profile_image',blank='True')
    

    def __str__(self):
        return self.user.username


def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender = User)

tutorial/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm

class RegistrationForm(UserCreationForm):
    # make email as a required info during registration
    # other info (i.e. first name) is optional
    email = forms.EmailField(required = True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            )
    def save(self, commit = True):
        user = super(RegistrationForm, self).save(commit = False)
        # get cleaned data just in case someone inputs some harmful strings
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.emial = self.cleaned_data['email']

        if commit:
            user.save()
        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
        )

tutorial/accounts/views.py
from django.shortcuts import render,redirect
#from django.contrib.auth.forms import UserCreationForm
from accounts.forms import (
    RegistrationForm, 
    EditProfileForm    
)
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
# import this b/c we want the current session to continue after the user changes password
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required


# Create your views here.

def home(request):
    numbers = [1,2,3,4,5]
    name = 'name is boo'
    args = {'myName':name,'allNumbers': numbers}
    return render(request,'accounts/home.html',args)

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account')
    else:
        form = RegistrationForm()
    
    args = {'form': form}
    return render(request, 'accounts/reg_form.html', args)


def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)

# This view has two parts: "if": saves user's changed info and redirect user to his profile pate
# "else": get this page when requested (direct the user to the edit page to change his info)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return redirect('/account/profile')
    else:
        form = EditProfileForm(instance = request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

# change user password with known old password

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data = request.POST, user = request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile')
        else:
            return redirect('/account/change-password')

    else:
        form = PasswordChangeForm(user = request.user)
        args = {'form': form}
        return render(request, 'accounts/change-password.html', args)

tutorial/tutorial/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('/account/login')

tutorial/accounts/templates/accounts/change-password.html
{% extends 'base.html' %} {%block head%}
<title>Change Password</title>
{% endblock %} {% block body %}
<div class="container">
    <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %} {%block head%}
<title>Profile</title>
{% endblock %} {% block body %}
<div class="container">
    <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>
{% endblock %}

tutorial/accounts/templates/accounts/home.html
{% extends 'base.html' %}

<h1>Homepage</h1>
{%block head%}
<title>Home</title>
{% endblock %} {% block body %}
<h1>Home</h1>
{% endblock %}

tutorial/accounts/templates/accounts/jinjaExample.html
<html>

<head>
    <title>Login</title>

    {% load static %}
    <link rel="stylesheet" href={% static 'accounts/style.css' %} type="text/css">
</head>

<body>
    <div class="container">
        <h1>Welcome</h1>
        Welcome, you can login here
        <button class="btn btn-default" type="button" name="buttom">login</button>
    </div>
    <div class="jumbotron">
        <h1>Welcome</h1>
    </div>
    <h1>{{ myName }}</h1>
    <ul>
        {% for number in allNumbers %}
        <li>{{ number }}</li>
        {% endfor %}
    </ul>

</body>

</html>

tutorial/accounts/templates/accounts/login.html
{% extends 'base.html' %} {% block body %}
<div class="container">
    <h1>Welcome</h1>
    <p>
        You can login here
    </p>
    <h2>Login</h2>
    <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">login</button>
    </form>
</div>

{% endblock %}

tutorial/accounts/templates/accounts/logout.html
{% extends 'base.html' %} {% block body %}
<div class="container">
    <h1>Logout</h1>
    <p>
        You have logged out
    </p>


</div>

{% endblock %}

tutorial/accounts/templates/accounts/profile.html
{% extends 'base.html' %} {%block head%}
<title>Profile</title>
{% endblock %} {% block body %}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
    <p>City: {{ user.userprofile.city }}</p>
    <p>Website: {{ user.userprofile.website }}</p>
    <img src="{{ user.userprofile.image.url }}" width="600">
</div>
{% endblock %}

tutorial/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %} {% block body %}
<div class="container">
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">submit</button>
    </form>
</div>

{% endblock %}

tutorial/accounts/templates/accounts/reset_password.html
{% extends 'base.html' %} {% block body %}
<div class="container">
    <h1>Password Reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>

{% endblock %}

tutorial/accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %} {% block body %}
<div class="container">
    <h1>Password reset complete</h1>
    <p>
        You have successfully reset your password. Now you can log in again.
    </p>
    <a href="{% url 'accounts:login' %}">Log in</a>
</div>

{% endblock %}

tutorial/accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %} {% block body %}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>

{% endblock %}

tutorial/accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %} {% block body %}
<div class="container">
    <h1>Password reset email sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly. If you don't receive an email, please make sure you've entered the address you registered with, and check your
        spam folder.
    </p>
</div>

{% endblock %}

tutorial/accounts/templates/accounts/reset_password_email.html
{% load i18n %} {% autoescape off %} {% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}. {% endblocktrans %} {% trans "Please go to the following page and choose a new password:"
%} {% block reset_link %} {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %} {% endblock %} {% trans "Your username, in case you've forgotten:" %} {{ user.get_username }} {% trans "Thanks for using our site!"
%} {% blocktrans %}The {{ site_name }} team {% endblocktrans %} {% endautoescape %}

tutorial/accounts/templates/base.html
<html>

<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Base</title>
    {% endblock %}
</head>


<body>
    <br>
    <div class="container">
        <!-- Static navbar -->
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                  <span class="sr-only">Toggle navigation</span>
                                  <span class="icon-bar"></span>
                                  <span class="icon-bar"></span>
                                  <span class="icon-bar"></span>                                  
                        </button>
                    <a class="navbar-brand" href="/">Social Network (Login App)</a>
                </div>
                <!--create buttons/links on the navigation bar-->
                <div id="navbar" class="navbar-collapse collapse">
                    {% if user.is_authenticated %}
                    <ul class="nav navbar-nav">
                        <li><a href="/account">Home</a></li>
                        <li><a href={% url 'accounts:view_profile' %}>Profile</a></li>
                        <li><a href={% url 'accounts:edit_profile' %}>Edit Profile</a></li>
                        <li><a href={% url 'accounts:change_password' %}>Change Password</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href={% url 'accounts:logout' %}>Log Out</a></li>
                    </ul>

                    {% else %}
                    <ul class="nav navbar-nav">
                        <li><a href={% url 'accounts:reset_password' %}>Reset Password</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/account/login">Login</a></li>
                        <li><a href="/account/register">Register</a></li>
                    </ul>
                    {% endif %}
                </div>
                <!--/.nav-collapse -->
            </div>
            <!--/.container-fluid -->
        </nav>
    </div>

    {% block body %}
    <h1>base</h1>
    {% endblock %}
</body>



</html>